### PR TITLE
Add cocoapod support

### PR DESCRIPTION
**Pull request by dvlprliu**
This PR adds the support for Cocoapod.

And there are some problems: 
- Since this repo aims to swift4, you should always `xcode-select -s /path/to/your/xcode9` before you `pod spec lint` this podspec.
- I deleted `s.description` property, because I don't know what to fill, you can fill that up, or you tell me what to fill, and I'll create a new commit on this PR.
- It's not been released to the cocoapod trunk yet.

### CODE REVIEW

**Comment by raulriera** [comment]
Thank you! I will test it out later today and merge once I can push it to the pod trunk 🙌

**Comment by raulriera** [comment]
Code and lint looks good, but can you do something about this? `[!] You (rieraraul@gmail.com) are not allowed to push new versions for this pod. The owners of this pod are jus0****@gmail.com.`

**Comment by dvlprliu** [comment]
Ok, I'll look into that.

**Comment by raulriera** [comment]
Oh never mind, that is not you... someone else has that name :( Let me think of something new I guess

**Comment by raulriera** [comment]
Thank you once again!

**Pull request merged**
